name: Render and Deploy Bookdown

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install pandoc
      uses: r-lib/actions/setup-pandoc@v1

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("bookdown", "rmarkdown"))'

    - name: Render book
      run: |
        Rscript -e 'bookdown::render_book("index.Rmd")'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
